### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by LiFuxiong** [lisswn/ssr-pagination#2]
集成进去,报错了

**Comment by lisswn** [comment]
是在nuxt里面用吗？需要nuxt.config.js中配置plugins作为插件引用

**Comment by lisswn** [comment]
> 集成进去,报错了

是在nuxt里面用吗？需要nuxt.config.js中配置plugins作为插件引用

**Comment by LiFuxiong** [comment]
<img width="387" alt="屏幕快照 2020-02-07 11 48 45" src="https://user-images.githubusercontent.com/14539746/73999549-0d013780-49a0-11ea-9a3e-dce4bcd485b5.png">
![WechatIMG422](https://user-images.githubusercontent.com/14539746/73999552-112d5500-49a0-11ea-9493-69da37ff0300.jpeg)
![WechatIMG423](https://user-images.githubusercontent.com/14539746/73999555-14c0dc00-49a0-11ea-84b8-449c82a8f348.jpeg)

在ssr设置为true的时候就报错了

**Comment by LiFuxiong** [comment]
<img width="467" alt="屏幕快照 2020-02-07 11 54 08" src="https://user-images.githubusercontent.com/14539746/73999734-9b75b900-49a0-11ea-85c8-c3f0eb644bf6.png">

<img width="584" alt="屏幕快照 2020-02-07 11 54 20" src="https://user-images.githubusercontent.com/14539746/74000026-99602a00-49a1-11ea-8918-0df25a20013a.png">


ssr设置为true, 就报了这个错误

**Comment by LiFuxiong** [comment]
用了,但是吧ssr设置true,就报错了
